env: order-dev20
person: 
  id: 2
  name: bbb
  address: BJ
#eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:8762/eureka
spring:
  application:
    name: order
  datasource:
    username: root
    password: 131480
    url: jdbc:mysql:///pm110?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.0.105
    username: guest
    password: guest
    port: 5672
server:
  port: 8089
PRODUCT:
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
