env: productdev
#eureka:
  #client:
   # service-url:
    #  defaultZone: http://localhost:8762/eureka
server:
  port: 8087
spring:
  application:
    name: product
  datasource:
    username: root
    password: 131480
    url: jdbc:mysql:///pm110?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.0.105
    username: guest
    password: guest
    port: 5672
